apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      volumes:
        - name: course-storage-volume
          persistentVolumeClaim:
            claimName: course-storage-claim
      containers:
        - name: log-output-app
          image: njugen/log_output:1.11
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: course-storage-volume
            mountPath: /usr/src/files
        - name: pong-app
          image: njugen/pong-app:1.11
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
          volumeMounts:
          - name: course-storage-volume
            mountPath: /usr/src/files