apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pong-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pong-app-service
            port:
              number: 1235
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pong-app-service
            port:
              number: 1234