apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-storage-claim
spec:
  storageClassName: course-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi