apiVersion: v1
kind: Service
metadata:
  name: pong-app-service
spec:
  type: ClusterIP
  selector:
    app: pong-app
  ports:
    - name: log-output-port
      port: 1234
      protocol: TCP
      targetPort: 3000
    - name: ping-pong-port
      port: 1235
      protocol: TCP
      targetPort: 3001