apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: file-storage
          emptyDir: {}
      containers:
        - name: log-output-get-text
          image: njugen/log_output:1.10
          imagePullPolicy: Always
          volumeMounts:
          - name: file-storage
            mountPath: /usr/src/files
          ports:
            - containerPort: 3000
        - name: log-output-set-text
          image: njugen/log_output:1.10
          imagePullPolicy: Always
          volumeMounts:
          - name: file-storage
            mountPath: /usr/src/files
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001